### ISSUE TITLE
Add Excavation Costs for Boring/Jacking Pit

### ISSUE THREAD

**Issue by dboatman** [besasm/Rehab---nBCR-Tools#10]
We currently calculate the volume of excavation required for the boring/jacking pit in our construction durations. We should be adding this excavation into the costs for the whole pipe replacement when boring/jacking (using the same costs we use for excavation on the mainline).

This cost is also missing in the DS tool.

**Comment by dboatman** [comment]
After further consideration, I'm unsure if this is built into the bid item, or if it falls under the general excavation bid item.

**Comment by MisterGardner** [comment]
This issue remains a question, but doesn't seem to drastically impact results.  Manholes only affect the BPW, APW, and cost of whole pipe actions for now, and the excavation costs play a great deal in the overall cost, changes to this cost would not be problematically significant except in very close nBCR values.
