### ISSUE TITLE
Remove MH Construction Duration from Bore/Jack

### ISSUE THREAD

**Issue by dboatman** [besasm/Rehab---nBCR-Tools#13]
The MH construction duration may be accounted for via the pit excavation duration for boring/jacking, thus should not be included in the duration calc for that alternative.

**Comment by MisterGardner** [comment]
Is this the same as #10

**Comment by dboatman** [comment]
Nope. There is construction duration (plays into traffic costs and bypass pumping), and then there is excavation direct costs ($/CY). #10 was referring to the latter. This is speaking of the former.

**Comment by MisterGardner** [comment]
Manhole replacement removed from boring/jacking duration calc (line 269 of COST_ESTIMATOR_ConstructionDurations).
