### ISSUE TITLE
Environmental mitigation costs checks hazmat presence?

### ISSUE THREAD

**Issue by nmccullar** [besasm/Rehab---nBCR-Tools#14]
DBO.COST_ESTIMATOR_WHOLE 

Line 202

This UPDATE is applying environmental mitigation costs for pipes crossing conservation and preservation areas.

But the query is filtering out lines WHERE B.Xcsi >0, the same as in in the previous UPDATE for hazardous materials. The process diagram suggests this should be looking at xEzonC and xEzonP instead of Xcsi.

Or does Xcsi somehow include xEzonC and xEzonP?

**Comment by MisterGardner** [comment]
Excellent catch!  Updated the procedure.
