### ISSUE TITLE
Checking backfill volume calcs

### ISSUE THREAD

**Issue by nmccullar** [besasm/Rehab---nBCR-Tools#16]
In DBO.COSTESTIMATOR_WHOLE might have two issues affecting backfill volumes.

1: Line 105, ExcavationVolume only goes down to the depth of the pipe, doesn't include OutsideDiameter or @PipeZoneDepthAdditionalInches.

2: Line 253, backfill calculations subtracts out the depth of the base course (which is correct) but it also subtracts out the extra width of the asphalt cut, which isn't included in the excavation volume.

**Comment by dboatman** [comment]
1. Excavation bid items only go to the pipe invert, per City of Portland specs 405.80c and do not include pipe bedding. I believe the pipe depth is to the invert.

405.80c:
"Sewer Pipe - Depth for calculating excavation volume for pipes will be
measured vertically from the invert of the pipe to original grade or new
road subgrade whichever is lower. No measurement will be made for the
extra excavation required for placement of pipe bedding. Backfill for pipe
will be measured from the top of the pipe zone to the original ground or
bottom of the new road subgrade whichever is less."

**Comment by dboatman** [comment]
1. Per 405.80c, it goes to the "original grade or new road subgrade". When I asked Joe E. from construction about this, he said that they've always billed to the surface (original grade), and he believes the "new road subgrade" was poorly worded language added to indicate that if the road elevation is changing, then the quantity goes to the new depth. As such, for our calculations, it seems we would use "original grade", which, unless I'm mistaken, would include asphalt, per Joe E. Thoughts on this?

**Comment by nmccullar** [comment]
Based on the sketch in today's standup and the TM 4.5 spreadsheet I think I have a better idea of what's going on. Excavation volume is fine. The problem is at line 253 where the backfill volumes are calculated.

Right now this looks like:
     FillAbovePipeZone = Excavation Volume - Base Course Volume - Pipe Volume

I think what we need is:
     FillAbovePipeZone = Excavation Volume - Base Course Volume - Pipe Zone Volume

Here's my suggestion for revising the calculations.

[Backfill Calcs snippet.txt](https://github.com/besasm/Rehab---nBCR-Tools/files/96724/Backfill.Calcs.snippet.txt)

**Comment by dboatman** [comment]
This would still be incorrect because it is taking excavation volume and subtracting out base coarse vol., part of which (the T-cuts) are not included in excavation volume. For this reason, in a past memo, I suggested recalculating using depths, then multiply by trench width to get back to vol/ft.

i.e.
FillAbovePipeZone = trench width \* (pipe depth - pipe zone height) \* (1 CY / 27 CF)

EDIT: Oops, looking back in my code, I messed that up off the top of my head. Here is the comment I have in the "Above Pipe Zone Volume" cell:

=above pipe zone depth_trench width_1 ft_(1 CY / 27 CF)
=(trench depth - pipe zone depth - agg depth-surface pave depth)_trench width/27     [CY/ft]
=(trench depth - pipe zone depth - 1 ft)*trench width/27     [CY/ft]

TM 4.5 was calculating as:
=Exc vol - pipe zone vol - pipe vol - asph vol
However, this is incorrect because the asphault volume is based on (trench width+1')

The agg + A/C turns into a 12", composed of 8" Agg + 4" A/C (assumed).

**Comment by nmccullar** [comment]
How about this?

FillAbovePipeZone = Excavation Volume - Trench Width \* ( Base Course Depth + Pipe Diameter + Pipe Zone Extra Depth) / 27

**Comment by dboatman** [comment]
I'm not sure what "Pipe Zone Extra Depth" is. Can you elaborate on that? Is that the 12" above the pipe?

The main issue I see with the calc is that it is missing the A/C depth in it.

Also, a very small discrepancy [that should probably be ignored] is that the invert is based on the inner diameter. So, if by "Pipe Diameter" you mean "inner diameter", then you need to add in the pipe thickness between the 12" above and the top of the pipe (inside). If you mean "outer diameter", then you need to subtract out the pipe thickness between the invert and the bedding.

**Comment by nmccullar** [comment]
"Pipe Zone Extra Depth" is the depth added to the outside diameter to find the total depth of the pipe zone. It says "at least 12"" in the construction specs, but it's 18" in the TM 4.5 spreadsheet, and 18" in the SQL and on the flow chart. I wonder if the extra six inches is meant to account for the difference between inside and outside diameter?

Edit: After the standup today we decided it's 12" above the pipe, plus 6" below.

**Comment by nmccullar** [comment]
If the TM 4.5 spreadsheet has been in use and produces satisfactory results, I think it's better for us to remain consistent with it. We've spotted some things that could be changed to improve those calculations, but for a planning level tool that other people need to understand, I think we can accept the imperfections.

My code snippet attached above matches the spreadsheet (I think), and I vote we go with that.

**Comment by MisterGardner** [comment]
Changes applied
