### ISSUE TITLE
Bypass flow calcs use depth instead of invert

### ISSUE THREAD

**Issue by nmccullar** [besasm/Rehab---nBCR-Tools#19]
The bypass pumping flow rate calculations are using pipe depth instead of pipe invert to find the pipe slope. This should be changed in the COST_ESTIMATOR_WHOLE on line 512, and in function GIS.COSTEST_Find_BypassPumpingUnitRate.

Edit: Also line 522

**Comment by MisterGardner** [comment]
Changed formula to use xPipSlope:
 (X.FRM_ELEV-X.TO_ELEV)/X.[length] 
from PipXP calcs
