### ISSUE TITLE
ASM Failure Action

### ISSUE THREAD

**Issue by JoeHoffman** [besasm/Rehab---nBCR-Tools#2]
![failure action](https://cloud.githubusercontent.com/assets/16583053/12156935/cc4391a4-b482-11e5-947f-305d5c5f880f.JPG)

Why is the failure action for this pipe a liner?  It has one bad spot with a CND defect so it would qualify as a spot repair.  I calculated the nbcr for the three alternatives in the attached spreadsheet.

[compkey_140314_20153112.xlsx](https://github.com/besasm/Rehab---nBCR-Tools/files/80459/compkey_140314_20153112.xlsx)

The values I calculated for nBCR are spot -0.025, line -5.91, dig -1.01.

**Comment by dboatman** [comment]
As mentioned before, it seems that the "2.5" failure action is off, but we get the correct answer in the end Gen 3 suggestion.

**Comment by MisterGardner** [comment]
This appears to be a case where the future costs impact the current decision (something that 3.0 accounts for).  Are we moving towards modifying the results of 2.5 to emulate results of 3.0 (accounting for future replacements)? Maybe we need to ask ourselves if the results of 2.5 should continue to exist at all?

**Comment by JenniferBW** [comment]
For consistency, I think we should be using the “lifecycle” cost of all actions, so – using the future costs associated with an action in all cases.

I’m not sure that the results of 2.5 (currently used for Base Risk in 3.0) do need to exist.  I would prefer that Gen 3.0 uses consistent methodology throughout for Base Risk and Alternate Risk.

Please help me understand if there is a reason not to make this consistent in methodology between Base Risk and Alternate Risk and keep the 2.5 outputs in the 3.0 process.

**Comment by MisterGardner** [comment]
It may be that we should just remove 2.5 calcs for nBCR entirely.  Then we can first select the highest nBCR solution from Gen3 as our primary solution.  Using that as the primary solution, we loop through it again to find the more realistic nBCR.  So for this particular pipe, Gen3 would use the nBCR value 11.49 (OC base risk, spot repair recommended), and on second pass, would give nBCR of 1.35 (spot repair base risk, spot repair recommended).

**Comment by MisterGardner** [comment]
I'll do a quick procedure to find how much this new approach changes our current recommended actions.

**Comment by MisterGardner** [comment]
The following query should end this debate.  It does the loop for primary best nBCR and then selects the secondary based on the primary recommendation.  Currently doesn't account for special cases such as surcharging and location, but it seems to work for most everything else:

SELECT  D.Compkey, maxnBCR, BaseRiskSolution, [MaxnBCRRecompile],
        CASE
          WHEN [MaxnBCRRecompile] = [nBCR_OC_OC]
               OR
               [MaxnBCRRecompile] = [nBCR_CIPP_OC]
               OR
               [MaxnBCRRecompile] = [nBCR_SP_OC]
          THEN 'OC' 
          WHEN [MaxnBCRRecompile] = [nBCR_OC_SP]
               OR
               [MaxnBCRRecompile] = [nBCR_CIPP_SP]
               OR
               [MaxnBCRRecompile] = [nBCR_SP_SP]
          THEN 'SP'
          WHEN [MaxnBCRRecompile] = [nBCR_OC_CIPP]
               OR
               [MaxnBCRRecompile] = [nBCR_CIPP_CIPP]
               OR
               [MaxnBCRRecompile] = [nBCR_SP_CIPP]
          THEN 'CIPP'
          END AS RecompileSolution
FROM    [REHAB].[GIS].[REHAB_Branches] AS D
        INNER JOIN
        (
SELECT Compkey, MaxnBCR, BaseRiskSolution,
  (SELECT Max(v) 
   FROM (VALUES (OCRecompare)
      ,(CIPPRecompare)
      ,(SPRecompare)) AS value(v)) as [MaxnBCRRecompile]
FROM 
(
SELECT  A.Compkey, maxnBCR,
        CASE
          WHEN maxnBCR = [nBCR_OC_OC]
               OR
               maxnBCR = [nBCR_CIPP_OC]
               OR
               maxnBCR = [nBCR_SP_OC]
          THEN 'OC' 
          WHEN maxnBCR = [nBCR_OC_SP]
               OR
               maxnBCR = [nBCR_CIPP_SP]
               OR
               maxnBCR = [nBCR_SP_SP]
          THEN 'SP'
          WHEN maxnBCR = [nBCR_OC_CIPP]
               OR
               maxnBCR = [nBCR_CIPP_CIPP]
               OR
               maxnBCR = [nBCR_SP_CIPP]
          THEN 'CIPP'
          END AS BaseRiskSolution,
          CASE
          WHEN maxnBCR = [nBCR_OC_OC]
               OR
               maxnBCR = [nBCR_CIPP_OC]
               OR
               maxnBCR = [nBCR_SP_OC]
          THEN [nBCR_OC_OC] 
          WHEN maxnBCR = [nBCR_OC_SP]
               OR
               maxnBCR = [nBCR_CIPP_SP]
               OR
               maxnBCR = [nBCR_SP_SP]
          THEN [nBCR_SP_OC]
          WHEN maxnBCR = [nBCR_OC_CIPP]
               OR
               maxnBCR = [nBCR_CIPP_CIPP]
               OR
               maxnBCR = [nBCR_SP_CIPP]
          THEN [nBCR_CIPP_OC]
          END AS OCRecompare,
          CASE
          WHEN maxnBCR = [nBCR_OC_OC]
               OR
               maxnBCR = [nBCR_CIPP_OC]
               OR
               maxnBCR = [nBCR_SP_OC]
          THEN [nBCR_OC_SP] 
          WHEN maxnBCR = [nBCR_OC_SP]
               OR
               maxnBCR = [nBCR_CIPP_SP]
               OR
               maxnBCR = [nBCR_SP_SP]
          THEN [nBCR_SP_SP]
          WHEN maxnBCR = [nBCR_OC_CIPP]
               OR
               maxnBCR = [nBCR_CIPP_CIPP]
               OR
               maxnBCR = [nBCR_SP_CIPP]
          THEN [nBCR_CIPP_SP]
          END AS SPRecompare,
          CASE
          WHEN maxnBCR = [nBCR_OC_OC]
               OR
               maxnBCR = [nBCR_CIPP_OC]
               OR
               maxnBCR = [nBCR_SP_OC]
          THEN [nBCR_OC_CIPP] 
          WHEN maxnBCR = [nBCR_OC_SP]
               OR
               maxnBCR = [nBCR_CIPP_SP]
               OR
               maxnBCR = [nBCR_SP_SP]
          THEN [nBCR_SP_CIPP]
          WHEN maxnBCR = [nBCR_OC_CIPP]
               OR
               maxnBCR = [nBCR_CIPP_CIPP]
               OR
               maxnBCR = [nBCR_SP_CIPP]
          THEN [nBCR_CIPP_CIPP]
          END AS CIPPRecompare
FROM    [REHAB].[GIS].[REHAB_Branches] AS A
        INNER JOIN
        (
SELECT Compkey,
  (SELECT Max(v) 
   FROM (VALUES ([nBCR_OC_OC])
      ,([nBCR_OC_CIPP])
      ,([nBCR_OC_SP])
      ,([nBCR_CIPP_OC])
      ,([nBCR_CIPP_CIPP])
      ,([nBCR_CIPP_SP])
      ,([nBCR_SP_OC])
      ,([nBCR_SP_CIPP])
      ,([nBCR_SP_SP])) AS value(v)) as [MaxnBCR]
FROM [REHAB].[GIS].[REHAB_Branches]
WHERE COMPKEY = 140314
) AS B
ON A.COMPKEY = B.COMPKEY
) AS C) AS E
ON E.COMPKEY = D.COMPKEY

**Comment by JenniferBW** [comment]
I asked Issac for clarification because I wanted to make sure I understood what he is saying.

I believe what he is saying is that it will work to use lifecycle costs for both the base risk and alternate risk, and one way we could do that is to perform two iterations on the nBCR.

The first iteration will be to run 2.5 to get the base risk (which is only based on the initial cost of the first action during an emergency repair), then run 3.0 to get the alternate risk (which is based on a lifecycle cost of the proactive action and the subsequent actions necessary over 180+ years), calculate the nBCRs (which may be inflated), select the option with the best nBCR.
Then the second iteration will be to run 3.0 using the option with the best nBCR from iteration 1 to calculate the base risk (which will be a lifecycle risk cost, taking into account the first emergency action and then subsequent necessary actions for 180+ years), then run 3.0 to get the alternate risk, and calculate a new final nBCR.

**Comment by MisterGardner** [comment]
This pipe is working as it should, giving a spot repair action in REHAB_Branches and 'Do Nothing' in nBCR_Data because the failure year is beyond the 20 year window.
