### ISSUE TITLE
Groundslope still partially in difficulty factor

### ISSUE THREAD

**Issue by nmccullar** [besasm/Rehab---nBCR-Tools#21]
Notes on the flow chart suggest ground slope > 10% is no longer being used as a category to get difficulty factor.

In the difficult area UPDATE statement of COST_ESTIMATOR_WHOLE, line 589, the filters aren't using groundslope as a variable, but the CASE WHEN statements still add a difficulty factor for high slopes.

**Comment by MisterGardner** [comment]
I believe we should still consider ground slope to be a difficulty factor.

**Comment by MisterGardner** [comment]
If the flow chart says no ground slope, it is possible it was missed on the last update?

**Comment by nmccullar** [comment]
The note says (greyed out) "pStrType null or 0, and gslope > 0.10 (no longer using per Trello 10/30/14)"

That's a while ago.

**Comment by dboatman** [comment]
I think it was removed due to the inaccuracy of the ground slope values. However, if that it deemed not a problem anymore, then I agree with Issac that it should be a part of difficult work area factors, given the feedback from that construction/ME mtg last year.

**Comment by yarrowm** [comment]
There are 2 issues: 
1) Is ground slope value valid, or still problematic? DME does not have reliable rim or depth values and should not be used to calculate ground slopes. MST_Nodes and MST_links are much much better for calculating ground slope. If there are null values in GrndElev, it is potentially a data QC issue and should be resolved in the data via a tech's support, not the code. If the node does not exist in MST_nodes, then we would need to use a DME value, which might be bogus. 
2) How are we using ground slope to estimate costs? It sounds like the code is just saying it is a difficult area. Is this true? If so, we need to update the documentation.

**Comment by MisterGardner** [comment]
I am wondering if we actually need to have the street comparison in there.  If anything, I'd think the lack of a street would make the work even more difficult in terms of shoring problems.  _EDIT_ ah, yeah, it looks like it only considers if there is no street at all.  I'm on board with that.

**Comment by dboatman** [comment]
Ok...so if in a street, no multiple (or rather multiplier = 1.0). If not, look at grnd slope and input 1.5x multiplier where max(seg gslope) > 0.1. Is this correct?

**Comment by MisterGardner** [comment]
correct.  I'll make the change on my end.
