### ISSUE TITLE
asphalt paving thickness

### ISSUE THREAD

**Issue by yarrowm** [besasm/Rehab---nBCR-Tools#24]
Per email from Joe H 1/20/16 regarding standup same day:

"In regard to the thickness of the asphalt concrete (as highlighted below).  We agreed to vary the thickness per road type and downtown area as follows:

![image](https://cloud.githubusercontent.com/assets/16343206/12561629/ffd402ec-c355-11e5-894e-ab00f54050b3.png)

"The cost estimator currently assumes 4 inches for all pipes.  But we know the street type in pipe xp, and should vary our costs to more closely match the construction details."

**Comment by dboatman** [comment]
After review of the TM-4.5, they dont even use the $18.69/CY price we pulled from them. If you look in any of the App. C's, they use ~41/SY. The $18.69/CY doesnt even work out mathematically for units from what Joe, myself, and Isaac could see. After looking at relevant bid data with Joe, and after conversions to the base CCI, the following costs would be suggested:
4": $28.62/SY ($35.70 current day)
6": $44.27/SY ($55.23 current day)
8": $55.77/SY ($69.57 current day)

**Comment by dboatman** [comment]
Even if the price is meant to be $18.69/SY (not CY), it is still lower than the cheapest we have ever gotten asphalt for, per all records, regardless of item quantity.

![image](https://cloud.githubusercontent.com/assets/16582500/12649351/17ce5b24-c593-11e5-99fd-68541431206f.png)

Backwards adjusting to our 2008 CCI, we get the average, lowest, and highest unit prices for those bid items as:
![image](https://cloud.githubusercontent.com/assets/16582500/12649466/845f5176-c593-11e5-9cd1-2c2ffbfec0d3.png)

**Comment by MisterGardner** [comment]
Applied to ASM cost estimator.
