### ISSUE TITLE
compkey 403425

### ISSUE THREAD

**Issue by JoeHoffman** [besasm/Rehab---nBCR-Tools#25]
![compkey 403425](https://cloud.githubusercontent.com/assets/16583053/12599218/f45bedf4-c444-11e5-843a-78bb7645bc37.JPG)

this pipe shows an action of open cut, but there are not near failed segments ( no grade 4 segments).  The pipe is grade 4 in Hansen, so we should be recommending continued monitoring ( monitor by inspection).

**Comment by MisterGardner** [comment]
Great spot Joe, I missed that in the update.

**Comment by MisterGardner** [comment]
I was running with a 40 year failure horizon.  Sorry about that.

**Comment by MisterGardner** [comment]
Shows open cut in REHAB_Branches (as it should if it has no failed segments AND has a failure year beyond 20 years from now).  Shows 'Do nothing' in nBCR_Data as it should due to failure year beyond 20 years from now.
