### ISSUE TITLE
compkey 135553

### ISSUE THREAD

**Issue by JoeHoffman** [besasm/Rehab---nBCR-Tools#26]
![compkey 135553](https://cloud.githubusercontent.com/assets/16583053/12599364/255a5d54-c446-11e5-9469-722cbdd04a5b.JPG)

This pipe has one bad segment.  The rest of the segments are grade 1 and 2.  It is being recommended for an open cut and the nbcr is positive.   Why is the spot repair not winning?  That is the correct answer for this pipe.

**Comment by MisterGardner** [comment]
The replacement cost of this pipe is only $85,000 vs the spot cost of $15,000.  Based on APW only, you save $20,000 over the recurring lifecycle of the pipe.  Based on APW and BPW, the OC option provides $40k worth of risk mitigation, and the SP option only provides $20k of risk mitigation.  This pipe also falls outside our 20 year action horizon.

**Comment by MisterGardner** [comment]
I think maybe there is a notion that this cost difference of $70,000 may become rampant.  Let me assure you, this new process is recommending far more spot repairs than open cuts when compared to previous incarnations.  It is just that this particular pipe is super cheap to dig up and replace, and saves the city more money in the long run. 

I'm guessing if there is something wrong here, the error can be found in my cost estimation or my COF.  I'll give it some more investigation.

**Comment by JoeHoffman** [comment]
It might be because we are adding the manhole cost to the spot cost which is dragging it down.  We should not include manhole cost in any nbcr calculation since we are not carrying manhole risk.

I am seeing a large number of pipes that are being recommended for open cut that were spot repair pipes in gen 2 ( which means that less than 10 percent of the pipe is near failed (> 1000 pts, grade 4) or previously failed (spot repairs).  In general, I would expect all of these pipes to remain spot repairs in Gen 3.  You might want to join Gen 2 spot repair whole pipes to Gen3 open cut recommendation to see how many pipes are in this situation and maybe spot a pattern.

**Comment by JoeHoffman** [comment]
I agree, for the most part the spot repair recommendations are working.  I am signing off for tonight.  I have to go pick up my kid.
Thanks
joe

**Comment by yarrowm** [comment]
I'm seeing that one as "Do nothing", with null values in the APWliner-spot-whole fields. Is this the correct data source? It's the same map you just sent me, Joe. Does this match your whole pipe data source?
![image](https://cloud.githubusercontent.com/assets/16343206/12600500/25f965d0-c44f-11e5-981f-348d980e0600.png)

**Comment by dboatman** [comment]
Hmmm...conflicts between the tables...

GIS.nBCR_Data:
![image](https://cloud.githubusercontent.com/assets/16582500/12618752/2791b66a-c4ca-11e5-85ed-8ba7ad9cdd79.png)

GIS.REHAB_Branches:
![image](https://cloud.githubusercontent.com/assets/16582500/12618772/3da08fe4-c4ca-11e5-8b6d-eaa91c1882e4.png)

**Comment by dboatman** [comment]
Wait...this is closed? What was the resolution?

**Comment by MisterGardner** [comment]
Rehab_Branches is ASM's internal data table.  Rehab_Branches should be seen as a more pure set of information than nBCR data.  nBCR_Data hides nBCRs and solutions that extend beyond the 20 year horizon, in order to keep operators from questioning why a solution is being presented for an object with more than 20 years of life left, or an nBCR less than 0.1, or a pipe that does not belong to BES, etc.

**Comment by yarrowm** [comment]
I think that you want to put the cards on the table, not hide numbers from people using data to make decisions. It is legitimate to say that we recommend no action for a pipe with 20+ year remaining useful life. We can discuss more later.

**Comment by MisterGardner** [comment]
This is not what has been discussed at length, by all parties involved.  Putting cards on the table has so far led to many questions of why recommendations are being made for things well beyond our action horizon despite having an attractive nBCR.  If we drop it again, I hope someone else will be doing the work to inevitably add it back in.

**Comment by yarrowm** [comment]
I'm not sure we're even talking about the same thing, so we should probably discuss as a group face to face.
