### ISSUE TITLE
Base Agg Price from TM-4.5

### ISSUE THREAD

**Issue by dboatman** [besasm/Rehab---nBCR-Tools#27]
Per discussions in standup, we've noted base agg prices from TM-4.5 in 2009 revised version jumps from ~$30/CY to $131.51, while A/C dropped to about half it's price (see #24). After review with Joe on historic bid data, the following is suggested:

![image](https://cloud.githubusercontent.com/assets/16582500/12655544/45299b9a-c5ae-11e5-9066-ca01fbb2dfa5.png)

**Comment by MisterGardner** [comment]
Does this close 24?

**Comment by MisterGardner** [comment]
Sorry, of course it doesn't.

**Comment by MisterGardner** [comment]
Applied changes to base course.
