### ISSUE TITLE
CIPP Regression Eqn

### ISSUE THREAD

**Issue by dboatman** [besasm/Rehab---nBCR-Tools#29]
Isaac and I just saw that the cost est. code is still using the old exponential regression equation. It seemed like the results we not too bad, but could potentially be weighted a bit more towards the smaller diameters we end up lining the most (historically). Here is a table summarizing a number of possibilities:

![image](https://cloud.githubusercontent.com/assets/16582500/12660960/ae40c410-c5cb-11e5-8d95-8e5a428782c8.png)

"All Data to Left Reg." is a trendline using all of the historic bid data since 2013, with quantities < 100 removed as outliers.

"DS CE Reg" is the current regression equation in use for the DS cost estimate tool.

"Exp. Eqn" is the current equation in use by the code for ASM nBCR Tool.:
=1.1406_(diam)^1.4882_length

"Data to left, each diam avg'd..." is if all of the data used for the "All Data to Left Reg." series were to be averaged for each diameter individually.

"Best fit of data avg pts" is the best fit equation for the previous columns averages.

The green columns are based on raw data. The yellow columns are regression equations.

**Comment by dboatman** [comment]
Here is the spreadsheet used to build the above table:

\besfile1\Systems_Planning\7977_Rehab\Phase 3\Cost Estimating Check\CIPP Unit Costs.xlsx

**Comment by MisterGardner** [comment]
Governing equation here seems to be Cost = 5.47 \* D - 10, with D in inches.

**Comment by yarrowm** [comment]
Per discussion today, Daniel has adjusted the "All Data to Left Reg" based cost values shown above to 2008 CCI by dividing by 1.25.

**Comment by dboatman** [comment]
Exactly, because the raw data to the left was all adjusted to current day CCI.

**Comment by MisterGardner** [comment]
Are we still discussing this?  I think Daniel is indicating a solution, but I'd like him to finalize his suggestion here before I apply it and close it out.

**Comment by dboatman** [comment]
The cost analysis for CIPP has been redone after discussions with Joe and Isaac and plans to make a table and not use a regression. I've now uploaded all of the cost analysis I've done for vetting/review. The workbook can be found here:
\besfile1\Systems_Planning\7977_Rehab\Phase 3\Cost Estimating Check\Unit Costs.xlsm

(Note: Github removes the first backslash in the path)

**Comment by MisterGardner** [comment]
Applied in [GIS].[COSTEST_Find_LinerCost], COST_ESTIMATOR_WHOLE, and COSTEST_LinerCostsTable
