### ISSUE TITLE
Duration for lining segments

### ISSUE THREAD

**Issue by yarrowm** [besasm/Rehab---nBCR-Tools#3]
Are you calculating duration for lining for whole pipes only, or just segments and then adding up later?

**Comment by MisterGardner** [comment]
I should only consider duration for lining on whole pipes.  It was wrong of me to allow for lining spots since we don't consider that an alternative yet.

**Comment by yarrowm** [comment]
My question is: Do you do the calculation on whole pipes or segment then add up to whole pipe?

**Comment by MisterGardner** [comment]
Calculate CIPP on whole pipes.
