### ISSUE TITLE
Action flags/recommended actions

### ISSUE THREAD

**Issue by yarrowm** [besasm/Rehab---nBCR-Tools#30]
- Have we abandoned action flags, or not? We still have an "action" field in rehab10ftsegs. is this valid? If still in use, can we verify their meaning because some of them did not match the lists that I have for action flags.
- If not in use, let's make sure we are using a system that gives us the information that we need. Our recommended actions are "Do nothing", "OC", "CIPP", "SP", and "OC Sandwich". We don't have "Watch me"??? Is there any way to know if the recommendation for a given pipe are solely based on nBCR, or if there is an exception or gate driving the recommendation? Is this enough information?

**Comment by dboatman** [comment]
Check out the Rehab_Branches table in REHAB database. There is a column labeled "Problems" that lists all of that kind of info in text format. I've asked Isaac to include this column in nBCR_Data table, so eventually it may be there as well.

**Comment by MisterGardner** [comment]
Action flags are to be abandoned.  Instead, they become 'problems' (misnomer due to my poor vocabulary).  As Daniel stated, I'm working on a way to present them in an organized way using nBCR_Data.

**Comment by MisterGardner** [comment]
This change has been implemented.  You will now find the 'problems' field in nCBR_Data.
