### ISSUE TITLE
Direct Construction Cost Factors: add or multiply?

### ISSUE THREAD

**Issue by nmccullar** [besasm/Rehab---nBCR-Tools#31]
Seems like the difficulty should be _multiplied_ by time adjustment factor rather than _added_.

COST_ESTIMATOR_WHOLE
Line 638:
DirectConstructionCost =  sum(costs) \* (difficulty + CurrentENR/BaseENR)

**Comment by dboatman** [comment]
Indeed it should! Nice catch!

**Comment by MisterGardner** [comment]
This was a great catch!  Noted and changed.
