### ISSUE TITLE
Poverty In Difficulty Factors

### ISSUE THREAD

**Issue by dboatman** [besasm/Rehab---nBCR-Tools#32]
Talking with Joe, he said that xSFR the other poverty column were not meant to be part of a difficulty multiplier on project cost...only on CoF. So, is it currently in the multiplicative difficulty factor? If so, it sounds like it should be removed.

**Comment by MisterGardner** [comment]
Looks to be part of project cost.  I'll  drop it to consequence only.  A 1.5 multiplier on CoF alone may be a bit high.  I'll run it both ways and analyze nBCRs on affected pipes just to be sure.

**Comment by MisterGardner** [comment]
My mistake.  It should only affect basement flooding, and is calculated in COF-0155 Basement Flooding.

**Comment by dboatman** [comment]
I've removed it from DS tool as well. Thanks for catching that @JoeHoffman !
