### ISSUE TITLE
Bypass flow calcs don't include reduction factor

### ISSUE THREAD

**Issue by nmccullar** [besasm/Rehab---nBCR-Tools#34]
The cost estimator diagram shows bypass flow as 1/5th of pipe capacity. This reduction is not reflected in the code.

**Comment by MisterGardner** [comment]
These are legacy equations, and we should definitely move to a 1/5th Mannings calc.

**Comment by MisterGardner** [comment]
Updated in [GIS].[COSTEST_Find_BypassPumpingUnitRate]
