### ISSUE TITLE
Maximum depth for manholes

### ISSUE THREAD

**Issue by nmccullar** [besasm/Rehab---nBCR-Tools#36]
The cost estimator diagram shows a maximum depth of 25' for manholes, but this isn't reflected in the code.

**Comment by dboatman** [comment]
See #18. Does this address the issue above?

**Comment by dboatman** [comment]
oops...didnt mean to close that...

**Comment by MisterGardner** [comment]
I don't feel capping manhole cost to depth of 25 feet would be a realistic representation of expense.  Unless we have evidence to the contrary, this should stay in the code and change in the diagram.

**Comment by dboatman** [comment]
Agreed as far as the costs go for additional footage. The 25' max is meant for the construction days, since the MH excavation would be replaced with the bore pit at that point.

**Comment by nmccullar** [comment]
Thanks, this will be changed in the diagram.
