### ISSUE TITLE
pipe construction duration totals - clarify please

### ISSUE THREAD

**Issue by yarrowm** [besasm/Rehab---nBCR-Tools#4]
Daniel’s diagram indicates base durations are added to manhole replacement, traffic mobilization, flow diversion, etc to get total durations. Are you adding like this to the pipe duration, or are you calculating manhole replacement, traffic control, flow diversion, etc. costs with these durations? If you are incorporating into a total construction duration, have we/you made any adjustments to the costs of those other items to adjust for the incorporation into the construction duration value for the various alternatives?

**Comment by MisterGardner** [comment]
Times are added.  Exception is 'CIPP with spots' and 'multiple spots'.  In these cases, the maximum time is used for the time table.  Then the maximum rate is used (as part of the cost estimator).

**Comment by MisterGardner** [comment]
Explanation is same as previous, except manhole times have been removed from liners and spots.
