### ISSUE TITLE
Pipe depth for spot repair

### ISSUE THREAD

**Issue by yarrowm** [besasm/Rehab---nBCR-Tools#6]
What are you using for depth in the spot repair duration calculation? Average segment depth as calculated elsewhere in the cost estimator, or something else?

**Comment by MisterGardner** [comment]
Depth for spot repairs is the average for the segment.  This number is take from PIPEXP (uDepth + dDepth)/2.0

**Comment by dboatman** [comment]
Is this resolved? I would ask Yarrow if it's ok to close, since she wrote it, but since she's out for a week, should we close it to tidy up?

**Comment by MisterGardner** [comment]
This looks resolved to me.
