### ISSUE TITLE
open cut depth

### ISSUE THREAD

**Issue by yarrowm** [besasm/Rehab---nBCR-Tools#7]
What are you using to calculate the depth for the open cut construction duration? Is it the average depth of the segment average depths, or Average upstream-downstream depth, or... A depth value is needed for trench excavation volume and manhole depths (issue #5).

**Comment by MisterGardner** [comment]
This is also (uDepth + dDepth)/2.0 from the  PIPEXP table.

**Comment by dboatman** [comment]
Is this resolved? I would ask Yarrow if it's ok to close, since she wrote it, but since she's out for a week, should we close it to tidy up?

**Comment by MisterGardner** [comment]
This also looks resolved to me.

**Comment by yarrowm** [comment]
Yes, this is resolved. Calculation applies to only whole pipes.
